@echo off
javac ./treevisitor/*.java
javac ./binarysearch/*.java
javac ./binarytree/*.java
javac ./bubblesort/*.java
javac ./factorial/*.java
javac ./linearsearch/*.java
javac ./quicksort/*.java
javac ./linkedlist/*.java