grammar MethodDeclaration;

methodDeclaration: PUBLIC type IDENTIFIER LPAREN LPAREN type IDENTIFIER LPAREN COMMA type IDENTIFIER RPAREN* RPAREN? RPAREN LBRACE LPAREN varDeclaration RPAREN* LPAREN statement RPAREN* RETURN expression SEMI RBRACE;
